### ISSUE TITLE
Questions about Docker usage

### ISSUE THREAD

**Issue by airidaceae** [rdaum/moor#19]
Hello! I have some questions about the specific way docker is being used in this project. I'd like some help understanding the purpose/usecase of having the whole project recompile itself with `cargo watch` while watching for changes.

In my experience with docker, this tends to make the image more bloated and run slower.

**Comment by rdaum** [comment]
This is for a development workflow/cycle. If you have concerns about performance, and your goal is to actually run the server for some production use (which it isn't really suited for yet) then yes you should create a version without watch. And with `--release` enabled.

**Comment by rdaum** [comment]
Should not it's not prohibitive to just run the binaries you want without docker at all. The setup there is really for example.  You just need to run e.g. `telnet-host` and `daemon` with the right args (see `-h` and the arguments used in the `docker-compose.yml`) .
