### ISSUE TITLE
`telnet-host` doesn't emit "I don't understand that." on core-less `huh`

### ISSUE THREAD

**Issue by abesto** [rdaum/moor#340]

**Comment by rdaum** [comment]
I would recommend working on top of my scheduler refactor pull request

**Comment by abesto** [comment]
# At first glance:

`RpcServer` *submits* a task when a `Command` request is received. and indeed, it responds accordingly, and that's it. there's no parsing involved, and neither the `RpcClient` nor `telnet-host` then ever check the result of that newly spawned task AFAICT. so there are a few options here:
* `RpcServer` should wait for the result of the task and respond accordingly (seems to be not desired because `CommandSubmitted` exists)
* do *some* processing before responding with `CommandSubmitted` (feels fragile)
* make `telnet-host` check the task. this is... probably not trivial, because we don't actually want to block?

# But then!

We first try to `do_command`, and we *do* actually wait for the task to finish there: https://github.com/rdaum/moor/blob/2cc08d35b1a252a11758ec5568cc50aa359b3edc/crates/daemon/src/rpc_server.rs#L763

In our case, this ends with an internal error 'cause there's no `do_command` in the core.

So presumably the play here is: also wait for the result of the `submit_command_task`?

**Comment by abesto** [comment]
Huh, and the returned RPC response is just `CommandSubmitted(task_id)`, even when we waited for the command task to finish, so presumably the intent is for the client to check for the result somehow?

**Comment by abesto** [comment]
Heh, I think I have a fix.

**Comment by abesto** [comment]
Soo the naive fix is:

```rust
        let task_id = parse_command_task_handle.task_id();
        self.clone().watch_command_task(parse_command_task_handle)?;
        Ok(RpcResponse::CommandSubmitted(task_id))
```

at the end of `perform_command`. This does make a newly-added test pass that exercises this case:

```
// The test core doesn't define a `huh` verb.
// Test that we get the correct default `huh` message.
% discombobulate
=I couldn't understand that.
```

HOWEVER! This also makes the already existing `suspend_read_notify` test fail:

```
58562 << 200
58562 >> ; return read(); "moot-line:4"; "TelnetMootRunner::eval";
58562 >> 201
thread 'test_suspend_read_notify' panicked at /home/abesto/moor/crates/moot/src/lib.rs:292:9:
assertion failed: `(left == right)`: Line 6

Diff < left / right > :
<None
>Some(
>    "\"201\"",
>)
```

**Comment by abesto** [comment]
Full code: https://github.com/rdaum/moor/pull/357

**Comment by abesto** [comment]
Printing `command` in `perform_command`:

```
[daemon]: [crates/daemon/src/rpc_server.rs:791:9] command = "; return read(); \"moot-line:4\"; \"TelnetMootRunner::eval\";"
```

Why are we even hitting `perform_command` in a `;` eval?

**Comment by abesto** [comment]
... oh, because `telnet-host` doesn't have special-casing for `;` evals. Which, fine, I guess? This *should* work then; if `RpcRequest::Command` is valid with a `;` eval, then both of these cases should work.
